import type { Metadata } from "next";
import { Tomorrow } from "next/font/google";
import "../globals.css";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import Header from "../../../components/header";

const tomorrow = Tomorrow({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Helldivers 2 Strategy Calculator",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale}>
      <body className={` ${tomorrow.className} antialiased bg-[#706969]`}>
        <NextIntlClientProvider>
          <nav>
            <Header></Header>
          </nav>

          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
