@startuml HelldiversStrategyCalculator
title Sequence Diagram - Strategy Generation

actor Client
participant StrategyFactory
participant MOParser
database API

Client --> API: Fetches the MO
Client --> Client: new StrategyFactory(currentMO)
Client --> StrategyFactory: generateNewStrategy()
StrategyFactory --> MOParser: isValidMO(currentMO)

alt Valid MO

    MOParser --> MOParser: Turns all Tasks into Objecitves
    MOParser --> StrategyFactory: Parsed MO
    StrategyFactory --> API: Gathers data to return the correct Strategy class
    StrategyFactory --> Client: Returns the CalculatorStrategy

else Invalid MO

    MOParser --> StrategyFactory: null
    StrategyFactory --> Client: null

end


@enduml